# syntax=docker/dockerfile:1.7

FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM deps AS dev
EXPOSE {{ frontend_port }}
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "{{ frontend_port }}"]
