//! Per-project marker file `.skap.toml` lives in each project root and
//! is meant to be committed. It carries enough metadata for `skap doctor`
//! and `skap clone` on a fresh checkout to know what we're looking at.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::utils::fs::write_atomic;

pub const FILE_NAME: &str = ".skap.toml";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectFile {
    pub project: ProjectMeta,
    #[serde(default)]
    pub ports: BTreeMap<String, u16>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectMeta {
    pub name: String,
    pub template: String,
    pub created: DateTime<Utc>,
}

impl ProjectFile {
    pub fn new(name: &str, template: &str, ports: BTreeMap<String, u16>) -> Self {
        Self {
            project: ProjectMeta {
                name: name.to_string(),
                template: template.to_string(),
                created: Utc::now(),
            },
            ports,
        }
    }

    pub fn load(dir: &Path) -> Result<Option<Self>> {
        let path = dir.join(FILE_NAME);
        if !path.exists() {
            return Ok(None);
        }
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let parsed: Self =
            toml::from_str(&raw).with_context(|| format!("failed to parse {}", path.display()))?;
        Ok(Some(parsed))
    }

    pub fn save(&self, dir: &Path) -> Result<()> {
        let path = dir.join(FILE_NAME);
        let header = "# Generated by skap. Commit this file – it lets `skap doctor`\n# and `skap clone` recognise the project on fresh checkouts.\n\n";
        let body = toml::to_string_pretty(self).context("failed to serialize .skap.toml")?;
        write_atomic(&path, &format!("{header}{body}"))
    }
}
